# Generated by Django 6.1 on 2026-08-17 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'occurred_at'], name='event_org_occurred_idx'), models.Index(fields=['organization', 'event_type'], name='event_org_type_idx')],
            },
        ),
    ]
