# Generated by Django 6.1 on 2026-08-17 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('identified_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'severity'], name='risk_org_severity_idx'), models.Index(fields=['organization', 'status'], name='risk_org_status_idx')],
            },
        ),
    ]
