# Generated by Django 6.1 on 2026-08-17 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('jira', 'Jira'), ('slack', 'Slack'), ('crm', 'CRM'), ('google_drive', 'Google Drive'), ('aws', 'AWS'), ('other', 'Other')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('active', 'Active'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('external_account_id', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'provider'], name='integration_org_provider_idx'), models.Index(fields=['organization', 'status'], name='integration_org_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider', 'name'), name='unique_integration_org_provider_name')],
            },
        ),
    ]
