# Generated by Django 6.1 on 2026-08-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'source', 'external_id'], name='event_org_source_external_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('organization', 'source', 'external_id'), name='unique_event_external_identity'),
        ),
    ]
