# Generated by Django 6.1 on 2026-09-27 19:37

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("core", "0012_documentcontent_documentchunk"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="document",
            name="embedding_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="embedding_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ready", "Ready"),
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.membership",
                    ),
                ),
            ],
        ),
    ]
